export enum PredicatesEnum {
  CONTAINS = 'Contains',
  DOES_NOT_CONTAN = 'Does not Contain',
  WAS_SOLD_BY = 'Was sold by',
  WAS_SOLD_TO = 'Was sold to',
  WAS_NOT_SOLD_BY = 'Was not sold by',
  WAS_NOT_SOLD_TO = 'Was not sold to',
  GREATER_THAN = 'Greater Than',
  LESS_THAN = 'Less Than',
  EQUAL_TO = 'Equal To',
  NOT_EQUAL_TO = 'Not Equal To',
  OTHER_THAN_THE_DEFAULT_VALUE = 'Other than the default value',
  SHOULD = 'Should Be',
  ARE = 'Are',
}
