import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';

import { OemQuotesUsers } from '../../intermediaries/_oem-quotes-users/oem-quotes-users.entity';
import { QuoteUserTypeEnum } from '../../intermediaries/_oem-quotes-users/oem-quotes-users.enums/quoteUserTypeEnum';
import { seedEntities } from '../../../utils/seed-factory.util';

export default ({ companyId = 1 }: { companyId?: number }) =>
  class CreateDemoOemQuoteUsers implements Seeder {
    public async run(factory: Factory, connection: Connection): Promise<any> {
      const quoteUsers: Partial<OemQuotesUsers>[] = [
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: true,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: true,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: true,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: true,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: false,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: false,
          isApprover: false,
          isEnabled: true,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
        {
          userId: 2,
          type: QuoteUserTypeEnum.INTERNAL,
          isOwner: true,
          isApprover: false,
          isEnabled: true,
          companyId,
          approvalStatus: null,
          isSavedAlertUser: false,
          isWorkflowUser: true,
        },
      ];

      const quoteUserEntities = await seedEntities(
        connection,
        OemQuotesUsers,
        quoteUsers,
      );

      return quoteUserEntities;
    }
  };
