import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';

import { OemPriceTierEntity } from '../../main/oem-price-tiers/oem-price-tier.entity';
import { seedEntities } from '../../../utils/seed-factory.util';

export default ({ companyId = 1 }: { companyId?: number }) =>
  class CreateDemoOemPriceTiers implements Seeder {
    public async run(factory: Factory, connection: Connection): Promise<any> {
      const priceTiers = [
        {
          unitTierId: 6,
          productId: 2,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 5,
          productId: 2,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 4,
          productId: 2,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 4,
          productId: 1,
          cogsUnit: 10,
          priceUnit: 10000,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 5,
          productId: 1,
          cogsUnit: 0,
          priceUnit: 1000,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 6,
          productId: 1,
          cogsUnit: 0,
          priceUnit: 100,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 8,
          productId: 1,
          cogsUnit: 1,
          priceUnit: 5,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 8,
          productId: 2,
          cogsUnit: 1,
          priceUnit: 30,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 7,
          productId: 2,
          cogsUnit: 1,
          priceUnit: 80,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 4,
          productId: 3,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 5,
          productId: 3,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 6,
          productId: 3,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 8,
          productId: 3,
          cogsUnit: 0,
          priceUnit: 50,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 6,
          productId: 2,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 5,
          productId: 2,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 9,
          productId: 5,
          cogsUnit: 0,
          priceUnit: 50,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 7,
          productId: 1,
          cogsUnit: 1,
          priceUnit: 10,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 7,
          productId: 3,
          cogsUnit: 0,
          priceUnit: 50,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 4,
          productId: 2,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 4,
          productId: 4,
          cogsUnit: 0,
          priceUnit: 10,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 5,
          productId: 4,
          cogsUnit: 0,
          priceUnit: 20,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 6,
          productId: 4,
          cogsUnit: 0,
          priceUnit: 0,
          isEnabled: false,
          companyId,
        },
        {
          unitTierId: 10,
          productId: 6,
          cogsUnit: 25,
          priceUnit: 100,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 11,
          productId: 6,
          cogsUnit: 25,
          priceUnit: 90,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 12,
          productId: 6,
          cogsUnit: 25,
          priceUnit: 80,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 13,
          productId: 6,
          cogsUnit: 25,
          priceUnit: 70,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 14,
          productId: 6,
          cogsUnit: 25,
          priceUnit: 60,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 10,
          productId: 7,
          cogsUnit: 40,
          priceUnit: 200,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 11,
          productId: 7,
          cogsUnit: 40,
          priceUnit: 190,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 12,
          productId: 7,
          cogsUnit: 40,
          priceUnit: 180,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 13,
          productId: 7,
          cogsUnit: 40,
          priceUnit: 170,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 14,
          productId: 7,
          cogsUnit: 40,
          priceUnit: 160,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 15,
          productId: 8,
          cogsUnit: 30,
          priceUnit: 50,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 15,
          productId: 9,
          cogsUnit: 100,
          priceUnit: 175,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 18,
          productId: 10,
          cogsUnit: 100,
          priceUnit: 150,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 16,
          productId: 10,
          cogsUnit: 100,
          priceUnit: 250,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 17,
          productId: 10,
          cogsUnit: 100,
          priceUnit: 200,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 19,
          productId: 11,
          cogsUnit: 100,
          priceUnit: 200,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 15,
          productId: 12,
          cogsUnit: 750,
          priceUnit: 1000,
          isEnabled: true,
          companyId,
        },
        {
          unitTierId: 15,
          productId: 13,
          cogsUnit: 300,
          priceUnit: 500,
          isEnabled: true,
          companyId,
        },
      ];

      const priceTierEntities = await seedEntities(
        connection,
        OemPriceTierEntity,
        priceTiers,
      );

      return priceTierEntities;
    }
  };
